const Koa = require('koa')
const parser = require('koa-bodyparser')
const catchError = require('./middlewares/exception')
require('./app/models/user')
const app = new Koa()
app.use(parser())
app.use(catchError)
const InitManager = require('./core/init')
InitManager.initCore(app)

app.listen(4000)